# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a5bb2a277c542a843ab38e9d75c867c142e10e2f1770b02863480508255ce5f5d321723a65774bbfa129e1e278e689eb0e226a3bbec12ff7c8c19df7a96fbc0

test:
  secret_key_base: 1facd1b39501a94155fa46fcaeba72f62b73a500387cfc2c77bb031831033e33873e5be8d2054e67c64129f31510bb6c48865b30c0805067d2f3e5a0f2b07250

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
